seml:
  name: rgnn_at_scale_attack_evasion_global_transfer
  executable: experiments/experiment_global_attack_transfer.py
  project_root_dir: ../..
  output_dir: config/attack_evasion_global_transfer/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 96G          # memory
    cpus-per-task: 4  # num cores
    time: 2-00:00     # max time, D-HH:MM
    partition: gpu_large

fixed:
  data_dir: data/
  artifact_dir: cache
  pert_adj_storage_type: evasion_global_transfer_adj
  pert_attr_storage_type: evasion_global_transfer_attr
  model_storage_type: pretrained
  surrogate_model_storage_type: pretrained
  device: 0
  data_device: 'cpu' 
  make_undirected: True
  # model_label: Soft Median PPRGo (T=30.0)

  dataset: ogbn-products

grid:
  seed:
    type: choice
    options:
      - 0
      # - 1
      # - 5
  model_label:
    type: choice
    options:
      - Vanilla GCN
      # - Vanilla GDC
      # - Soft Median GDC (T=5.0)
      # - Vanilla PPRGo
      # - Soft Median PPRGo (T=5.0)
      # - Soft Median PPRGo (T=1.0)

  epsilons: 
    type: choice
    options:
    - [0]
    # - [0.01]
    # - [0.05]
    # - [0.2]
    - [0.25]
    # - [0.5]

greedy_rbcd:
  fixed:
    attack: GreedyRBCD
    binary_attr: False
    # surrogate_model_label: Vanilla GCN (surrogate)
    surrogate_model_label: Vanilla GCN
    attack_params:
      search_space_size: 10_000_000
      do_synchronize: True
      loss_type: MCE

# prbcd:
#   fixed:
#     attack: PRBCD
#     binary_attr: False
#     surrogate_model_label: Vanilla GCN (surrogate)
#     attack_params:
#       keep_heuristic: WeightOnly
#       search_space_size: 10_000_000
#       do_synchronize: True
#       lr_factor: 5e4
#       attack_params: tanhMargin

# dice:
#   fixed:
#     attack: DICE
#     binary_attr: False
#     surrogate_model_label: Vanilla GCN (surrogate)